name: agri_guide
description: A guide for agricultural services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.3
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.3
  meta: ^1.1.8
  flutter_bloc: ^6.0.1
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4
  injectable: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.1
  freezed: ^0.9.2
  injectable_generator: ^1.0.4
  lint: ^1.2.0

flutter:
  uses-material-design: true
